routes/admin.php
<?php


use Illuminate\Support\Facades\Route;

// Login
    Route::get('admin-control/mobile', 'admin\MobileController@index');
    Route::get('admin-control/reset-password', 'admin\ResetpasswordController@index');

Route::group(['prefix' => 'admin-control', 'middleware' => 'guest'], function() {
    Route::get( '/', [ 'as' => 'login', 'uses' => 'admin\UserController@login'] );
    Route::post( 'login-auth', 'admin\UserController@auth' );
});

// Logout

Route::group(['prefix' => 'admin-control', 'middleware' => 'auth'], function() {
    Route::get( 'logout', 'admin\UserController@logout' );
    Route::get( 'dashboard', ['as' => 'home', 'uses' => 'admin\DashboardController@index' ]  );

// dashboard

    Route::get('dashboard','admin\DashboardController@index');
    

// survey

    Route::get('survey', 'admin\SurveyController@index');    
    Route::get('survey/add','admin\SurveyController@add');
    Route::post('survey/add','admin\SurveyController@adddata');
    Route::get('survey/edit/{id}', 'admin\SurveyController@edit');
    Route::post('survey/edit/{id}', 'admin\SurveyController@editdata');
    Route::get('survey/remove/{id}','admin\SurveyController@remove');
    Route::post('survey/removeMultiple','admin\SurveyController@removeMultiple');    


// offer-list

    Route::get('offer-list', 'admin\OfferlistController@index');
    Route::get('offer-list/add','admin\OfferlistController@add');
    Route::post('offer-list/add','admin\OfferlistController@adddata');
    Route::get('offer-list/edit/{id}', 'admin\OfferlistController@edit');
    Route::post('offer-list/edit/{id}', 'admin\OfferlistController@editdata');
    Route::get('offer-list/remove/{id}','admin\OfferlistController@remove');
    Route::post('offer-list/removeMultiple','admin\OfferlistController@removeMultiple');

// category

    Route::get('category', 'admin\CategoryController@index');
    Route::get('category/add', 'admin\CategoryController@add');
    Route::post('category/add', 'admin\CategoryController@adddata');
    Route::get('category/edit/{id}', 'admin\CategoryController@edit');
    Route::post('category/edit/{id}', 'admin\CategoryController@editdata');
    Route::get('category/remove/{id}','admin\CategoryController@remove');
    Route::post('category/removeMultiple','admin\CategoryController@removeMultiple');
    
// Faqs

    Route::get('faqs', 'admin\FaqsController@index');
    Route::get('faqs/add','admin\FaqsController@add');
    Route::post('faqs/add','admin\FaqsController@adddata');
    Route::get('faqs/edit/{id}', 'admin\FaqsController@edit');
    Route::post('faqs/edit/{id}', 'admin\FaqsController@editdata');
    Route::get('faqs/remove/{id}','admin\FaqsController@remove');
    Route::post('faqs/removeMultiple','admin\FaqsController@removeMultiple');

// pages

    Route::get('pages', 'admin\PagesController@index');
    Route::get('pages/edit/{id}', 'admin\PagesController@edit');
    Route::post('pages/edit/{id}', 'admin\PagesController@editdata');
    Route::post('pages/removeMultiple','admin\PagesController@removeMultiple');

// Setting

    Route::get('setting', 'admin\SettingController@index');
    Route::get('setting/edit/{id}', 'admin\SettingController@edit');
    Route::post('setting/edit/{id}', 'admin\SettingController@editdata');

    

// change password

    Route::get('/change-password', 'admin\ChangepasswordController@index');
    Route::post('/change-password','admin\ChangepasswordController@changePassword');


// Wallet

    Route::get('/wallet/credit', 'admin\CreditController@credit');
    Route::get('/wallet/debit', 'admin\DebitController@debit');
    Route::get('/wallet/remove/{id}', 'admin\WalletController@remove');
    Route::get('/wallet/removeMultiple', 'admin\WalletController@removeMultiple');

    // Route::get('/wallet', 'admin\WalletController@excel')->name('export_excel.excel');
    Route::get('/wallet/credit/export', 'admin\CreditController@exportCsv')->name('credit_export_wallet');
    Route::get('/wallet/debit/export', 'admin\DebitController@exportCsv')->name('debit_export_wallet');
    Route::get('/wallet/debit/status/{id}', 'admin\DebitController@change_status')->name('change_status_wallet');

// Offer Histories

    Route::get('/offer-histories','admin\OfferhistoriesController@index'); 
    Route::get('/offer-histories/remove/{id}', 'admin\OfferhistoriesController@remove');
    Route::get('/offer-histories/removeMultiple', 'admin\OfferhistoriesController@removeMultiple');
     Route::get('/offer-histories/status/{id}', 'admin\OfferhistoriesController@change_status')->name('change_status');

// Offer Histories

    Route::get('/offer-histories','admin\OfferhistoriesController@index'); 
    Route::get('/offer-histories/remove/{id}', 'admin\OfferhistoriesController@remove');
    Route::get('/offer-histories/removeMultiple', 'admin\OfferhistoriesController@removeMultiple');
     Route::get('/offer-histories/status/{id}', 'admin\OfferhistoriesController@change_status')->name('change_status');
      Route::get('/offer-histories/export', 'admin\OfferhistoriesController@exportCsv')->name('offer_export');

     

// Survey Histories

    Route::get('/survey-histories', 'admin\SurveyhistoriesController@index');
    Route::get('/survey-histories/remove/{id}', 'admin\SurveyhistoriesController@remove');
    Route::get('/survey-histories/removeMultiple', 'admin\SurveyhistoriesController@removeMultiple');
    Route::get('/survey-histories/export', 'admin\SurveyhistoriesController@exportCsv')->name('survey_export');
    
    

// Customer List
    Route::get('/customer-list', 'admin\CustomerlistController@index');
    Route::get('/customer-list/remove/{id}', 'admin\CustomerlistController@remove');
    Route::get('/customer-list/removeMultiple', 'admin\CustomerlistController@removeMultiple');
    Route::get('/customer-list/status/{customer}', 'admin\CustomerlistController@change_status')->name('change_customer_status');

// Forgot Password
// Password Reset Routes...
    Route::get('/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset.token');
    Route::post('/reset', 'ResetPasswordController@reset');
    
// Spin Wheels
    Route::get('/spin', 'admin\SpinController@index');
    Route::get('spin/edit/{id}', 'admin\SpinController@edit');
    Route::post('spin/edit/{id}', 'admin\SpinController@editdata');

// Paytm

    Route::get('/initiate','admin\PaytmController@initiate')->name('initiate.payment');
    Route::post('/payment','admin\PaytmController@pay')->name('make.payment');
    Route::post('/payment/status', 'admin\PaytmController@paymentCallback')->name('status');
    Route::get('/initiate/{id}', 'admin\DebitController@payNow');
    
// All Pages Controllers

    Route::get('/charts','admin\ChartsController@index');
    Route::get('/widgets','admin\WidgetsController@index');
    Route::get('/tables','admin\TablesController@index');
    Route::get('/grid','admin\GridController@index');
    Route::get('/form-basic','admin\BasicformController@index');
    Route::get('/form-wizard','admin\FormwizardController@index');
    Route::get('/page-button','admin\PagebuttonController@index');
    Route::get('/icon-material','admin\IconmaterialController@index');
    Route::get('/icon-fontawesome','admin\IconfontawesomeController@index');
    Route::get('/page-element','admin\PageelementController@index');
    Route::get('/index2','admin\Index2Controller@index');
    Route::get('/pages-gallery','admin\PagegalleryController@index');
    Route::get('/page-calendar','admin\PagecalendarController@index');
    Route::get('/page-invoice','admin\PageinvoiceController@index');
    Route::get('/page-chat','admin\PagechatController@index');
    Route::get('/authentication-login','admin\AuthenticationloginController@index');
    Route::get('/authentication-register','admin\AuthenticationregisterController@index');
    Route::get('/error-403','admin\Error403Controller@index');
    Route::get('/error-404','admin\Error404Controller@index');
    Route::get('/error-405','admin\Error405Controller@index');
    Route::get('/error-500','admin\Error500Controller@index');

    // Route::post('news/add','admin\NewsController@adddata');
    // Route::get('news/edit/{id}', 'admin\NewsController@edit');
    // Route::post('news/edit/{id}', 'admin\NewsController@editdata');

    // Route::get('news/remove/{id}','admin\NewsController@remove');
});


    

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index'); 
Route::get('/contact', 'HomeController@contact');
Route::post('ajax_request', 'HomeController@enquiry')->name('ajax-route');
Route::get('/{slug}', 'HomeController@pages'); 
// Route::get('/charts', 'ChartsController@index'); 
Route::get('/spin-wheel/{user:referal_code}', 'SpinWheelController@index');
Route::post('/spin-wheel/save', 'SpinWheelController@save'); 
// Route::get('/charts', 'ChartsController@index'); 



    

app/Http/Controllers/admin/CategoryController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Model\Category;
class CategoryController extends Controller{
   
    public function index(request $request){
        //
        $query = Category::withCount('offers')->latest();

        if( !empty( $request->name ) ) {
            $query->where('name', 'LIKE', '%'.$request->name.'%');
        }
        $lists1 = $query->paginate(20);

        $data = compact( 'lists1' ); // Variable to array convert
        return view('backend.inc.category.index', $data);
    }
    

    

   
    public function add()
    {
        //
        return view('backend.inc.category.add');
    }

    
    public function addData(Request $request)
    {
        //
        $rules = [
            'name'        => 'required'
            
            
        ];
        $request->validate( $rules );
        // $file = $request->file('image');
        // $destinationPath = 'public/imgs/shop/';
        // $file->move($destinationPath,$file->getClientOriginalName());

        
           

        

        $obj = new Category;
        $obj->name        = $request->name;
        
        
        // $obj->image  = $request->$file->getClientOriginalName();
        
        $obj->save();

        return redirect( url('admin-control/category/') )->with('success', 'Success! New record has been added.');
    }

   
    public function edit(Request $request,$id)
    {
        //
        $edit = Category::findOrFail( $id )->toArray();
        $request->replace($edit);
        $request->flash();

        return view('backend.inc.category.edit');
    }

    
    public function editData(Request $request, $id)
    {
        //
        $rules = [
            'name'        => 'required'
            
        ];
        $request->validate( $rules );
        // $file = $request->file('image');
        // $destinationPath = 'public/imgs/shop/';
        // $file->move($destinationPath,$file->getClientOriginalName());
        // $filename    = $file->getClientOriginalName();
        // $image_resize = Image::make($file->getRealPath());              
        // $image_resize->resize(300, 300);
        // $image_resize->save(public_path('imgs/survey/' .$filename));

        $obj = Category::findOrFail( $id );
        $obj->name        = $request->name;
        
        
        // $obj->image  = $request->$file->getClientOriginalName();
        $obj->save();

        return redirect( url('admin-control/category') )->with('success', 'Success! A record has been updated.');
    }
     public function remove(  $id ){
        $remove = Category::where('id',$id)->delete();
        return redirect( url('admin-control/category') )->with('success', 'Success! A record has been deleted.');   
    }

    public function removeMultiple(Request $request)
    {
        $check = $request->check; // input type="checkbox" name="check[]"
        Category::whereIn("id", $check)->delete(); // DELETE FROM news WHERE news_id IN (3,5,4)

        return redirect()->back()->with('success', 'Item(s) removed.');
    }

   
}

resources/views/backend/inc/category/add.blade.php
@extends('backend.layout.master')

@section('title','category')

@section('contant')


		<div class="page-wrapper p-5">

			@if( $errors->any() )
	            <div class="alert alert-danger" style="color: red;">
	                @foreach($errors->all() as $error)
	                    <li>{!! $error !!}</li>
	                @endforeach
	            </div>
	        @endif

	        @if (\Session::has('success'))
	            <div class="alert alert-success" style="color: green">
	                {!! \Session::get('success') !!}</li>
	            </div>
	        @endif

	        @if (\Session::has('danger'))
	            <div class="alert alert-danger" style="color: red;">
	                {!! \Session::get('danger') !!}</li>
	            </div>
	        @endif
	        <h2 style="text-align: center;">Add Category</h2>

	        {{ Form::open()  }}
		        <p class="">
		            {{ Form::label('name') }}
		            {{ Form::text('name', '', ['class' => 'form-control','placeholder' => 'Category']) }}
		        </p>
		        <p class="">
		            {{ Form::submit('Save', ['class' => 'login-btn btn btn-orange']) }}
		        </p>
		    {{ Form::close() }}

		   

		    </div>
@stop
		    	
				    

			
		
	

resources/views/backend/inc/category/edit.blade.php
@extends('backend.layout.master')

@section('title','category')

@section('contant')


		<div class="page-wrapper p-5">

			@if( $errors->any() )
	            <div class="alert alert-danger" style="color: red;">
	                @foreach($errors->all() as $error)
	                    <li>{!! $error !!}</li>
	                @endforeach
	            </div>
	        @endif

	        @if (\Session::has('success'))
	            <div class="alert alert-success" style="color: green">
	                {!! \Session::get('success') !!}</li>
	            </div>
	        @endif

	        @if (\Session::has('danger'))
	            <div class="alert alert-danger" style="color: red;">
	                {!! \Session::get('danger') !!}</li>
	            </div>
	        @endif
	        <h2 style="text-align: center;">Edit Category</h2>

	        {{ Form::open()  }}
		        <p class="">
		            {{ Form::label('name') }}
		            {{ Form::text('name', '', ['class' => 'form-control','placeholder' => 'Category']) }}
		        </p>
		        <p class="">
		            {{ Form::submit('Save', ['class' => 'login-btn btn btn-orange']) }}
		        </p>
		    {{ Form::close() }}

		    

		
	</div>
	@stop

resources/views/backend/inc/category/index.blade.php
@extends('backend.layout.master')

@section('title','category')

@section('contant')


		<div class="page-wrapper p-5">

			@if( $errors->any() )
	            <div class="alert alert-danger" style="color: red;">
	                @foreach($errors->all() as $error)
	                    <li>{!! $error !!}</li>
	                @endforeach
	            </div>
	        @endif

	        @if (\Session::has('success'))
	            <div class="alert alert-success" style="color: green">
	                {!! \Session::get('success') !!}</li>
	            </div>
	        @endif

	        @if (\Session::has('danger'))
	            <div class="alert alert-danger" style="color: red;">
	                {!! \Session::get('danger') !!}</li>
	            </div>
	        @endif
	        

		    <h2 style="text-align: center; padding: 50px 0;"> Category</h2>

		    <div>
		    	
				    

			<div class="row">
		        <div class="col-lg-3">
		            {!! Form::open(['method' => 'GET']) !!}
		                <div class="input-group my-3">
		                    {!! Form::text('name','',['class' => 'form-control', 'placeholder' => 'Search...'])!!}
		                    <div class="input-group-append">
		                        
		                    {{ Form::submit('search', ['class'=>'btn btn-primary']) }}
		                    </div>
		                </div>
		            {!! Form::close() !!}

		        </div>
		        <div class="col-lg-7"></div>
		        <div class="col-lg-2">
		        	<a href="{{ url('admin-control/category/add') }}" class="btn btn-primary add-btn-right float-right"><i class="mdi mdi-plus"></i> Add Category</a>
		        </div>
		        
		    </div>
		    {{ Form::open( ['url' => url('admin-control/category/removeMultiple'), 'method'=>'post'] ) }}
		    <div class="card">
		        <div class="card-body">
		            @if( !$lists1->isEmpty() )
		            <div class="">
		                <div class="row mb-3 ">
		                    <div class="col float-left" style="font-size: 18px;">{{ $lists1->firstItem() }} - {{ $lists1->lastItem() }} out of {{ $lists1->total() }} record(s) showing.                
		                    </div>
		                    <div class="col text-right">
		                    	
		                        <button type="button" class="btn btn-primary btn-remove"><i class="icon-bin"></i></button>
		                    </div>
		                </div>
	        			<div class="table-responsive">
					        <table border="1" style="width: 100%" class="table table-bordered">
					            <thead style="background: #1F262D; color: #fff;">
					                <tr>
					                	<th></th>
					                    <th>S.No.</th>
					                    <th>Name</th>
					                    <th>Action</th>
					                   
					                </tr>
					            </thead>
					            <tbody>
					                @php
					                $sn = $lists1->firstItem();
					                @endphp
					                @foreach( $lists1 as $list )
					                <tr>
					                	<td>
					                	@if(!$list->offers_count)
					                	{{ Form::checkbox('check[]',$list->id, '',['class'=>'check']) }}
					                	@else
		                    					-
	                     				@endif
					                	</td>

					                    <td>{{ $sn++ }}.</td>
					                    <td>{{ $list->name }} </td>
					                    <td>
					                    	@if(!$list->offers_count)
						                    	<a href="{{ url('admin-control/category/edit/'.$list->id) }}">EDIT</a>&nbsp;|
		                    					<a href="{{ url('admin-control/category/remove/'.$list->id) }}"onclick="return confirm('Are you sure you want to delete this item?');">DELETE</a>
		                    				@else
		                    					{{ $list->offers_count }} offers / survey found.
	                     					@endif
	                    				</td>
					                    
					                </tr>
					                @endforeach
					            </tbody>
					        </table>
					    </div>
					    {{ $lists1->links() }}
					    @else
			            No Record Found
			            @endif
				        
				    </div>

				   
		    </div>
		</div>
	    {{  Form::close()  }}

@stop